package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 购物车表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Carters implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 购物车编号. */
	private Integer carterId;

	/** 商品编号. */
	private Integer goodsId;

	/** 购物车数量. */
	private Integer carterNumbers;

	/** 用户编号. */
	private Integer userId;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Carters() {
	}

	/**
	 * 购物车编号 傪愝掕偟傑偡.
	 * 
	 * @param carterId
	 *            购物车编号
	 */
	public void setCarterId(Integer carterId) {
		this.carterId = carterId;
	}

	/**
	 * 购物车编号 傪庢摼偟傑偡.
	 * 
	 * @return 购物车编号
	 */
	public Integer getCarterId() {
		return this.carterId;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsId
	 *            商品编号
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsId() {
		return this.goodsId;
	}

	/**
	 * 购物车数量 傪愝掕偟傑偡.
	 * 
	 * @param carterNumbers
	 *            购物车数量
	 */
	public void setCarterNumbers(Integer carterNumbers) {
		this.carterNumbers = carterNumbers;
	}

	/**
	 * 购物车数量 傪庢摼偟傑偡.
	 * 
	 * @return 购物车数量
	 */
	public Integer getCarterNumbers() {
		return this.carterNumbers;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userId
	 *            用户编号
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carterId == null) ? 0 : carterId.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Carters other = (Carters) obj;
		if (carterId == null) {
			if (other.carterId != null) {
				return false;
			}
		} else if (!carterId.equals(other.carterId)) {
			return false;
		}

		return true;
	}

}
