package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 收藏夹表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Collectors implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 收藏夹编号. */
	private Integer collectid;

	/** 收藏时间. */
	private String collecttime;

	/** 分类名称. */
	private String classify;

	/** 商品编号. */
	private Integer goodsid;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Collectors() {
	}

	/**
	 * 收藏夹编号 傪愝掕偟傑偡.
	 * 
	 * @param collectid
	 *            收藏夹编号
	 */
	public void setCollectid(Integer collectid) {
		this.collectid = collectid;
	}

	/**
	 * 收藏夹编号 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹编号
	 */
	public Integer getCollectid() {
		return this.collectid;
	}

	/**
	 * 收藏时间 傪愝掕偟傑偡.
	 * 
	 * @param collecttime
	 *            收藏时间
	 */
	public void setCollecttime(String collecttime) {
		this.collecttime = collecttime;
	}

	/**
	 * 收藏时间 傪庢摼偟傑偡.
	 * 
	 * @return 收藏时间
	 */
	public String getCollecttime() {
		return this.collecttime;
	}

	/**
	 * 分类名称 傪愝掕偟傑偡.
	 * 
	 * @param classify
	 *            分类名称
	 */
	public void setClassify(String classify) {
		this.classify = classify;
	}

	/**
	 * 分类名称 傪庢摼偟傑偡.
	 * 
	 * @return 分类名称
	 */
	public String getClassify() {
		return this.classify;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((collectid == null) ? 0 : collectid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Collectors other = (Collectors) obj;
		if (collectid == null) {
			if (other.collectid != null) {
				return false;
			}
		} else if (!collectid.equals(other.collectid)) {
			return false;
		}

		return true;
	}

}
