package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 收藏夹表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Collections implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 收藏夹编号. */
	private Integer collectionId;

	/** 加入时间. */
	private String collectionsJoinTime;

	/** 商品编号. */
	private Integer goodsId;

	/** 分类名称. */
	private String sortsName;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Collections() {
	}

	/**
	 * 收藏夹编号 傪愝掕偟傑偡.
	 * 
	 * @param collectionId
	 *            收藏夹编号
	 */
	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	/**
	 * 收藏夹编号 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹编号
	 */
	public Integer getCollectionId() {
		return this.collectionId;
	}

	/**
	 * 加入时间 傪愝掕偟傑偡.
	 * 
	 * @param collectionsJoinTime
	 *            加入时间
	 */
	public void setCollectionsJoinTime(String collectionsJoinTime) {
		this.collectionsJoinTime = collectionsJoinTime;
	}

	/**
	 * 加入时间 傪庢摼偟傑偡.
	 * 
	 * @return 加入时间
	 */
	public String getCollectionsJoinTime() {
		return this.collectionsJoinTime;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsId
	 *            商品编号
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsId() {
		return this.goodsId;
	}

	/**
	 * 分类名称 傪愝掕偟傑偡.
	 * 
	 * @param sortsName
	 *            分类名称
	 */
	public void setSortsName(String sortsName) {
		this.sortsName = sortsName;
	}

	/**
	 * 分类名称 傪庢摼偟傑偡.
	 * 
	 * @return 分类名称
	 */
	public String getSortsName() {
		return this.sortsName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((collectionId == null) ? 0 : collectionId.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Collections other = (Collections) obj;
		if (collectionId == null) {
			if (other.collectionId != null) {
				return false;
			}
		} else if (!collectionId.equals(other.collectionId)) {
			return false;
		}

		return true;
	}

}
