package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 商品表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Goods implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品编号. */
	private Integer goodsId;

	/** 商品名称. */
	private String goodsName;

	/** 品牌名. */
	private String goodsBrand;

	/** 商品价格. */
	private Double goodsPrice;

	/** 商品数量. */
	private Integer goodsNumbers;

	/** 商品图片. */
	private String goodsImage;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Goods() {
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsId
	 *            商品编号
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsId() {
		return this.goodsId;
	}

	/**
	 * 商品名称 傪愝掕偟傑偡.
	 * 
	 * @param goodsName
	 *            商品名称
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	/**
	 * 商品名称 傪庢摼偟傑偡.
	 * 
	 * @return 商品名称
	 */
	public String getGoodsName() {
		return this.goodsName;
	}

	/**
	 * 品牌名 傪愝掕偟傑偡.
	 * 
	 * @param goodsBrand
	 *            品牌名
	 */
	public void setGoodsBrand(String goodsBrand) {
		this.goodsBrand = goodsBrand;
	}

	/**
	 * 品牌名 傪庢摼偟傑偡.
	 * 
	 * @return 品牌名
	 */
	public String getGoodsBrand() {
		return this.goodsBrand;
	}

	/**
	 * 商品价格 傪愝掕偟傑偡.
	 * 
	 * @param goodsPrice
	 *            商品价格
	 */
	public void setGoodsPrice(Double goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	/**
	 * 商品价格 傪庢摼偟傑偡.
	 * 
	 * @return 商品价格
	 */
	public Double getGoodsPrice() {
		return this.goodsPrice;
	}

	/**
	 * 商品数量 傪愝掕偟傑偡.
	 * 
	 * @param goodsNumbers
	 *            商品数量
	 */
	public void setGoodsNumbers(Integer goodsNumbers) {
		this.goodsNumbers = goodsNumbers;
	}

	/**
	 * 商品数量 傪庢摼偟傑偡.
	 * 
	 * @return 商品数量
	 */
	public Integer getGoodsNumbers() {
		return this.goodsNumbers;
	}

	/**
	 * 商品图片 傪愝掕偟傑偡.
	 * 
	 * @param goodsImage
	 *            商品图片
	 */
	public void setGoodsImage(String goodsImage) {
		this.goodsImage = goodsImage;
	}

	/**
	 * 商品图片 傪庢摼偟傑偡.
	 * 
	 * @return 商品图片
	 */
	public String getGoodsImage() {
		return this.goodsImage;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((goodsId == null) ? 0 : goodsId.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Goods other = (Goods) obj;
		if (goodsId == null) {
			if (other.goodsId != null) {
				return false;
			}
		} else if (!goodsId.equals(other.goodsId)) {
			return false;
		}

		return true;
	}

}
