package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 订单详情表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OrderDetails implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单详情表编号. */
	private Integer itemId;

	/** 商品编号. */
	private Integer goodsId;

	/** 商品数量. */
	private Integer goodsNumbers;

	/** 订单编号. */
	private Integer orderId;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public OrderDetails() {
	}

	/**
	 * 订单详情表编号 傪愝掕偟傑偡.
	 * 
	 * @param itemId
	 *            订单详情表编号
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * 订单详情表编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单详情表编号
	 */
	public Integer getItemId() {
		return this.itemId;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsId
	 *            商品编号
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsId() {
		return this.goodsId;
	}

	/**
	 * 商品数量 傪愝掕偟傑偡.
	 * 
	 * @param goodsNumbers
	 *            商品数量
	 */
	public void setGoodsNumbers(Integer goodsNumbers) {
		this.goodsNumbers = goodsNumbers;
	}

	/**
	 * 商品数量 傪庢摼偟傑偡.
	 * 
	 * @return 商品数量
	 */
	public Integer getGoodsNumbers() {
		return this.goodsNumbers;
	}

	/**
	 * 订单编号 傪愝掕偟傑偡.
	 * 
	 * @param orderId
	 *            订单编号
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public Integer getOrderId() {
		return this.orderId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OrderDetails other = (OrderDetails) obj;
		if (itemId == null) {
			if (other.itemId != null) {
				return false;
			}
		} else if (!itemId.equals(other.itemId)) {
			return false;
		}

		return true;
	}

}
