package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 订单表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单编号. */
	private Integer orderId;

	/** 下单时间. */
	private String orderTime;

	/** 订单状态. */
	private String orderStates;

	/** 用户编号. */
	private Integer userId;

	/** 订单地址. */
	private String orderAddress;

	/** 订单备注. */
	private String orderRemark;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Orders() {
	}

	/**
	 * 订单编号 傪愝掕偟傑偡.
	 * 
	 * @param orderId
	 *            订单编号
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public Integer getOrderId() {
		return this.orderId;
	}

	/**
	 * 下单时间 傪愝掕偟傑偡.
	 * 
	 * @param orderTime
	 *            下单时间
	 */
	public void setOrderTime(String orderTime) {
		this.orderTime = orderTime;
	}

	/**
	 * 下单时间 傪庢摼偟傑偡.
	 * 
	 * @return 下单时间
	 */
	public String getOrderTime() {
		return this.orderTime;
	}

	/**
	 * 订单状态 傪愝掕偟傑偡.
	 * 
	 * @param orderStates
	 *            订单状态
	 */
	public void setOrderStates(String orderStates) {
		this.orderStates = orderStates;
	}

	/**
	 * 订单状态 傪庢摼偟傑偡.
	 * 
	 * @return 订单状态
	 */
	public String getOrderStates() {
		return this.orderStates;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userId
	 *            用户编号
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * 订单地址 傪愝掕偟傑偡.
	 * 
	 * @param orderAddress
	 *            订单地址
	 */
	public void setOrderAddress(String orderAddress) {
		this.orderAddress = orderAddress;
	}

	/**
	 * 订单地址 傪庢摼偟傑偡.
	 * 
	 * @return 订单地址
	 */
	public String getOrderAddress() {
		return this.orderAddress;
	}

	/**
	 * 订单备注 傪愝掕偟傑偡.
	 * 
	 * @param orderRemark
	 *            订单备注
	 */
	public void setOrderRemark(String orderRemark) {
		this.orderRemark = orderRemark;
	}

	/**
	 * 订单备注 傪庢摼偟傑偡.
	 * 
	 * @return 订单备注
	 */
	public String getOrderRemark() {
		return this.orderRemark;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (orderId == null) {
			if (other.orderId != null) {
				return false;
			}
		} else if (!orderId.equals(other.orderId)) {
			return false;
		}

		return true;
	}

}
