package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 用户信息表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户编号. */
	private Integer userid;

	/** 用户名称. */
	private String username;

	/** 用户密码. */
	private String password;

	/** 用户昵称. */
	private String userNickname;

	/** 用户头像. */
	private String userImage;

	/** 用户性别. */
	private String userSex;

	/** 用户年龄. */
	private Integer userAge;

	/** 电话号码. */
	private String userNumber;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Users() {
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 用户名称 傪愝掕偟傑偡.
	 * 
	 * @param username
	 *            用户名称
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * 用户名称 傪庢摼偟傑偡.
	 * 
	 * @return 用户名称
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * 用户密码 傪愝掕偟傑偡.
	 * 
	 * @param password
	 *            用户密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 用户密码 傪庢摼偟傑偡.
	 * 
	 * @return 用户密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * 用户昵称 傪愝掕偟傑偡.
	 * 
	 * @param userNickname
	 *            用户昵称
	 */
	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	/**
	 * 用户昵称 傪庢摼偟傑偡.
	 * 
	 * @return 用户昵称
	 */
	public String getUserNickname() {
		return this.userNickname;
	}

	/**
	 * 用户头像 傪愝掕偟傑偡.
	 * 
	 * @param userImage
	 *            用户头像
	 */
	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	/**
	 * 用户头像 傪庢摼偟傑偡.
	 * 
	 * @return 用户头像
	 */
	public String getUserImage() {
		return this.userImage;
	}

	/**
	 * 用户性别 傪愝掕偟傑偡.
	 * 
	 * @param userSex
	 *            用户性别
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/**
	 * 用户性别 傪庢摼偟傑偡.
	 * 
	 * @return 用户性别
	 */
	public String getUserSex() {
		return this.userSex;
	}

	/**
	 * 用户年龄 傪愝掕偟傑偡.
	 * 
	 * @param userAge
	 *            用户年龄
	 */
	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	/**
	 * 用户年龄 傪庢摼偟傑偡.
	 * 
	 * @return 用户年龄
	 */
	public Integer getUserAge() {
		return this.userAge;
	}

	/**
	 * 电话号码 傪愝掕偟傑偡.
	 * 
	 * @param userNumber
	 *            电话号码
	 */
	public void setUserNumber(String userNumber) {
		this.userNumber = userNumber;
	}

	/**
	 * 电话号码 傪庢摼偟傑偡.
	 * 
	 * @return 电话号码
	 */
	public String getUserNumber() {
		return this.userNumber;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}

		return true;
	}

}
